export { filesApi } from './api/files.api'
export { useFileStore } from './model/file.store'
export type { FileNode } from './model/file.store'
export { default as BreadcrumbsNav } from './ui/BreadcrumbsNav.vue'
export { default as FileExplorer } from './ui/FileExplorer.vue'
export { default as FileSearchModal } from './ui/FileSearchModal.vue'
export { default as FileTreeNode } from './ui/FileTreeNode.vue'

// Composables
export { useAnalysisStatus } from './composables/useAnalysisStatus'
export type { AffectedFile, ImpactResult } from './composables/useAnalysisStatus'
export { useFileExplorer } from './composables/useFileExplorer'
export { useFileQuickOpen } from './composables/useFileQuickOpen'
export type { QuickOpenResult, UseFileQuickOpenOptions } from './composables/useFileQuickOpen'
export { useFileSearch } from './composables/useFileSearch'
export { provideHoveredFile, useHoveredFile } from './composables/useHoveredFile'
export { useIgnoreRules } from './composables/useIgnoreRules'
export { useQuickFilters } from './composables/useQuickFilters'
export { useQuickLook } from './composables/useQuickLook'
export { useTreeKeyboardNavigation } from './composables/useTreeKeyboardNavigation'

